name: IPO Alert

on:
  schedule:
    # 每天 UTC 时间 0:00 执行（即北京时间 8:00）
    - cron: '0 1 * * *'
  # 可选：允许手动触发
  workflow_dispatch:

jobs:
  send-ipo-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 pandas

      - name: Run IPO email script
        env:
          YAHOO_EMAIL: ${{ secrets.YAHOO_EMAIL }}
          YAHOO_APP_PASSWORD: ${{ secrets.YAHOO_APP_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: |
          python hk_ipo_aastocks.py
